Dev migrere fra snake case til camel case
navikt/pleiepengesoknad-mottak pull request #13
Opened 2020-04-30 09:31 UTC by SanderOpperud

2020-05-04 07:48 UTC, ramrock93 approved these changes
👍

2020-05-12 09:49 UTC, ramrock93 requested changes
Se kommentar .

2020-05-12 09:49 UTC, ramrock93 commented on src/main/kotlin/no/nav/helse/PleiepengesoknadMottak.kt
> -    install(MicrometerMetrics) {
Denne her må tilbake på plass. Vi får ellers ingen metrics på ktor requests.

2020-05-12 10:15 UTC, SanderOpperud commented on src/main/kotlin/no/nav/helse/PleiepengesoknadMottak.kt
> -    install(MicrometerMetrics) {
Usikker hvorfor den er fjernet, men har lagt den til nå iallfall :P

2020-05-13 12:34 UTC, merged